package com.olie.mybatis.mapper;

import com.olie.mybatis.model.ScheduleTask;
import com.olie.mybatis.model.ScheduleTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ScheduleTaskMapper {


    @Select("select * from schedule_task order by id")
    List<ScheduleTask> findAllWithRowBounds(RowBounds rowBounds);

    @Select("select * from schedule_task order by id")
    List<ScheduleTask> findAllWithParam(@Param("pageNum") int pageNum,
                                  @Param("pageSize") int pageSize);







    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    long countByExample(ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    int deleteByExample(ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    @Delete({
        "delete from schedule_task",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    @Insert({
        "insert into schedule_task (item_no, task_type, ",
        "business_no, schedule_time, ",
        "schedule_count, schedule_limit, ",
        "schedule_status, condition1, ",
        "condition2, fail_msg, ",
        "create_time, create_pin, ",
        "update_time, update_pin, ",
        "sys_version, yn, ",
        "ts)",
        "values (#{itemNo,jdbcType=INTEGER}, #{taskType,jdbcType=INTEGER}, ",
        "#{businessNo,jdbcType=VARCHAR}, #{scheduleTime,jdbcType=TIMESTAMP}, ",
        "#{scheduleCount,jdbcType=INTEGER}, #{scheduleLimit,jdbcType=INTEGER}, ",
        "#{scheduleStatus,jdbcType=INTEGER}, #{condition1,jdbcType=TINYINT}, ",
        "#{condition2,jdbcType=TINYINT}, #{failMsg,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createPin,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updatePin,jdbcType=VARCHAR}, ",
        "#{sysVersion,jdbcType=INTEGER}, #{yn,jdbcType=TINYINT}, ",
        "#{ts,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ScheduleTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    int insertSelective(ScheduleTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    List<ScheduleTask> selectByExampleWithRowbounds(ScheduleTaskExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    List<ScheduleTask> selectByExample(ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    @Select({
        "select",
        "id, item_no, task_type, business_no, schedule_time, schedule_count, schedule_limit, ",
        "schedule_status, condition1, condition2, fail_msg, create_time, create_pin, ",
        "update_time, update_pin, sys_version, yn, ts",
        "from schedule_task",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.olie.mybatis.mapper.ScheduleTaskMapper.BaseResultMap")
    ScheduleTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") ScheduleTask record, @Param("example") ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    int updateByExample(@Param("record") ScheduleTask record, @Param("example") ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ScheduleTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    @Update({
        "update schedule_task",
        "set item_no = #{itemNo,jdbcType=INTEGER},",
          "task_type = #{taskType,jdbcType=INTEGER},",
          "business_no = #{businessNo,jdbcType=VARCHAR},",
          "schedule_time = #{scheduleTime,jdbcType=TIMESTAMP},",
          "schedule_count = #{scheduleCount,jdbcType=INTEGER},",
          "schedule_limit = #{scheduleLimit,jdbcType=INTEGER},",
          "schedule_status = #{scheduleStatus,jdbcType=INTEGER},",
          "condition1 = #{condition1,jdbcType=TINYINT},",
          "condition2 = #{condition2,jdbcType=TINYINT},",
          "fail_msg = #{failMsg,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_pin = #{createPin,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_pin = #{updatePin,jdbcType=VARCHAR},",
          "sys_version = #{sysVersion,jdbcType=INTEGER},",
          "yn = #{yn,jdbcType=TINYINT},",
          "ts = #{ts,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ScheduleTask record);
}