package com.olie.mybatis.model;

import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

@Data
public class ScheduleTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.id
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.item_no
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Integer itemNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.task_type
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Integer taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.business_no
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private String businessNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.schedule_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Date scheduleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.schedule_count
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Integer scheduleCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.schedule_limit
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Integer scheduleLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.schedule_status
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Integer scheduleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.condition1
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Byte condition1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.condition2
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Byte condition2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.fail_msg
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private String failMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.create_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.create_pin
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private String createPin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.update_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.update_pin
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private String updatePin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.sys_version
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Integer sysVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.yn
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Byte yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.ts
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.id
     *
     * @return the value of schedule_task.id
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.id
     *
     * @param id the value for schedule_task.id
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.item_no
     *
     * @return the value of schedule_task.item_no
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Integer getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withItemNo(Integer itemNo) {
        this.setItemNo(itemNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.item_no
     *
     * @param itemNo the value for schedule_task.item_no
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setItemNo(Integer itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.task_type
     *
     * @return the value of schedule_task.task_type
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withTaskType(Integer taskType) {
        this.setTaskType(taskType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.task_type
     *
     * @param taskType the value for schedule_task.task_type
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.business_no
     *
     * @return the value of schedule_task.business_no
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public String getBusinessNo() {
        return businessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withBusinessNo(String businessNo) {
        this.setBusinessNo(businessNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.business_no
     *
     * @param businessNo the value for schedule_task.business_no
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setBusinessNo(String businessNo) {
        this.businessNo = businessNo == null ? null : businessNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.schedule_time
     *
     * @return the value of schedule_task.schedule_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withScheduleTime(Date scheduleTime) {
        this.setScheduleTime(scheduleTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.schedule_time
     *
     * @param scheduleTime the value for schedule_task.schedule_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.schedule_count
     *
     * @return the value of schedule_task.schedule_count
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Integer getScheduleCount() {
        return scheduleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withScheduleCount(Integer scheduleCount) {
        this.setScheduleCount(scheduleCount);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.schedule_count
     *
     * @param scheduleCount the value for schedule_task.schedule_count
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setScheduleCount(Integer scheduleCount) {
        this.scheduleCount = scheduleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.schedule_limit
     *
     * @return the value of schedule_task.schedule_limit
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Integer getScheduleLimit() {
        return scheduleLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withScheduleLimit(Integer scheduleLimit) {
        this.setScheduleLimit(scheduleLimit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.schedule_limit
     *
     * @param scheduleLimit the value for schedule_task.schedule_limit
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setScheduleLimit(Integer scheduleLimit) {
        this.scheduleLimit = scheduleLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.schedule_status
     *
     * @return the value of schedule_task.schedule_status
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Integer getScheduleStatus() {
        return scheduleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withScheduleStatus(Integer scheduleStatus) {
        this.setScheduleStatus(scheduleStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.schedule_status
     *
     * @param scheduleStatus the value for schedule_task.schedule_status
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setScheduleStatus(Integer scheduleStatus) {
        this.scheduleStatus = scheduleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.condition1
     *
     * @return the value of schedule_task.condition1
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Byte getCondition1() {
        return condition1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withCondition1(Byte condition1) {
        this.setCondition1(condition1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.condition1
     *
     * @param condition1 the value for schedule_task.condition1
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setCondition1(Byte condition1) {
        this.condition1 = condition1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.condition2
     *
     * @return the value of schedule_task.condition2
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Byte getCondition2() {
        return condition2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withCondition2(Byte condition2) {
        this.setCondition2(condition2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.condition2
     *
     * @param condition2 the value for schedule_task.condition2
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setCondition2(Byte condition2) {
        this.condition2 = condition2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.fail_msg
     *
     * @return the value of schedule_task.fail_msg
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public String getFailMsg() {
        return failMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withFailMsg(String failMsg) {
        this.setFailMsg(failMsg);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.fail_msg
     *
     * @param failMsg the value for schedule_task.fail_msg
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg == null ? null : failMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.create_time
     *
     * @return the value of schedule_task.create_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.create_time
     *
     * @param createTime the value for schedule_task.create_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.create_pin
     *
     * @return the value of schedule_task.create_pin
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public String getCreatePin() {
        return createPin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withCreatePin(String createPin) {
        this.setCreatePin(createPin);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.create_pin
     *
     * @param createPin the value for schedule_task.create_pin
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setCreatePin(String createPin) {
        this.createPin = createPin == null ? null : createPin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.update_time
     *
     * @return the value of schedule_task.update_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.update_time
     *
     * @param updateTime the value for schedule_task.update_time
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.update_pin
     *
     * @return the value of schedule_task.update_pin
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public String getUpdatePin() {
        return updatePin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withUpdatePin(String updatePin) {
        this.setUpdatePin(updatePin);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.update_pin
     *
     * @param updatePin the value for schedule_task.update_pin
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setUpdatePin(String updatePin) {
        this.updatePin = updatePin == null ? null : updatePin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.sys_version
     *
     * @return the value of schedule_task.sys_version
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Integer getSysVersion() {
        return sysVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withSysVersion(Integer sysVersion) {
        this.setSysVersion(sysVersion);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.sys_version
     *
     * @param sysVersion the value for schedule_task.sys_version
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setSysVersion(Integer sysVersion) {
        this.sysVersion = sysVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.yn
     *
     * @return the value of schedule_task.yn
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Byte getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withYn(Byte yn) {
        this.setYn(yn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.yn
     *
     * @param yn the value for schedule_task.yn
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setYn(Byte yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.ts
     *
     * @return the value of schedule_task.ts
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTask withTs(Date ts) {
        this.setTs(ts);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.ts
     *
     * @param ts the value for schedule_task.ts
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemNo=").append(itemNo);
        sb.append(", taskType=").append(taskType);
        sb.append(", businessNo=").append(businessNo);
        sb.append(", scheduleTime=").append(scheduleTime);
        sb.append(", scheduleCount=").append(scheduleCount);
        sb.append(", scheduleLimit=").append(scheduleLimit);
        sb.append(", scheduleStatus=").append(scheduleStatus);
        sb.append(", condition1=").append(condition1);
        sb.append(", condition2=").append(condition2);
        sb.append(", failMsg=").append(failMsg);
        sb.append(", createTime=").append(createTime);
        sb.append(", createPin=").append(createPin);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updatePin=").append(updatePin);
        sb.append(", sysVersion=").append(sysVersion);
        sb.append(", yn=").append(yn);
        sb.append(", ts=").append(ts);
        sb.append("]");
        return sb.toString();
    }
}