package com.olie.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScheduleTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public ScheduleTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andItemNoIsNull() {
            addCriterion("item_no is null");
            return (Criteria) this;
        }

        public Criteria andItemNoIsNotNull() {
            addCriterion("item_no is not null");
            return (Criteria) this;
        }

        public Criteria andItemNoEqualTo(Integer value) {
            addCriterion("item_no =", value, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoNotEqualTo(Integer value) {
            addCriterion("item_no <>", value, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoGreaterThan(Integer value) {
            addCriterion("item_no >", value, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_no >=", value, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoLessThan(Integer value) {
            addCriterion("item_no <", value, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoLessThanOrEqualTo(Integer value) {
            addCriterion("item_no <=", value, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoIn(List<Integer> values) {
            addCriterion("item_no in", values, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoNotIn(List<Integer> values) {
            addCriterion("item_no not in", values, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoBetween(Integer value1, Integer value2) {
            addCriterion("item_no between", value1, value2, "itemNo");
            return (Criteria) this;
        }

        public Criteria andItemNoNotBetween(Integer value1, Integer value2) {
            addCriterion("item_no not between", value1, value2, "itemNo");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNull() {
            addCriterion("task_type is null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNotNull() {
            addCriterion("task_type is not null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeEqualTo(Integer value) {
            addCriterion("task_type =", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotEqualTo(Integer value) {
            addCriterion("task_type <>", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThan(Integer value) {
            addCriterion("task_type >", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_type >=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThan(Integer value) {
            addCriterion("task_type <", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThanOrEqualTo(Integer value) {
            addCriterion("task_type <=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIn(List<Integer> values) {
            addCriterion("task_type in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotIn(List<Integer> values) {
            addCriterion("task_type not in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeBetween(Integer value1, Integer value2) {
            addCriterion("task_type between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("task_type not between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andBusinessNoIsNull() {
            addCriterion("business_no is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNoIsNotNull() {
            addCriterion("business_no is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNoEqualTo(String value) {
            addCriterion("business_no =", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoNotEqualTo(String value) {
            addCriterion("business_no <>", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoGreaterThan(String value) {
            addCriterion("business_no >", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoGreaterThanOrEqualTo(String value) {
            addCriterion("business_no >=", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoLessThan(String value) {
            addCriterion("business_no <", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoLessThanOrEqualTo(String value) {
            addCriterion("business_no <=", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoLike(String value) {
            addCriterion("business_no like", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoNotLike(String value) {
            addCriterion("business_no not like", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoIn(List<String> values) {
            addCriterion("business_no in", values, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoNotIn(List<String> values) {
            addCriterion("business_no not in", values, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoBetween(String value1, String value2) {
            addCriterion("business_no between", value1, value2, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoNotBetween(String value1, String value2) {
            addCriterion("business_no not between", value1, value2, "businessNo");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeIsNull() {
            addCriterion("schedule_time is null");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeIsNotNull() {
            addCriterion("schedule_time is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeEqualTo(Date value) {
            addCriterion("schedule_time =", value, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeNotEqualTo(Date value) {
            addCriterion("schedule_time <>", value, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeGreaterThan(Date value) {
            addCriterion("schedule_time >", value, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("schedule_time >=", value, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeLessThan(Date value) {
            addCriterion("schedule_time <", value, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeLessThanOrEqualTo(Date value) {
            addCriterion("schedule_time <=", value, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeIn(List<Date> values) {
            addCriterion("schedule_time in", values, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeNotIn(List<Date> values) {
            addCriterion("schedule_time not in", values, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeBetween(Date value1, Date value2) {
            addCriterion("schedule_time between", value1, value2, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleTimeNotBetween(Date value1, Date value2) {
            addCriterion("schedule_time not between", value1, value2, "scheduleTime");
            return (Criteria) this;
        }

        public Criteria andScheduleCountIsNull() {
            addCriterion("schedule_count is null");
            return (Criteria) this;
        }

        public Criteria andScheduleCountIsNotNull() {
            addCriterion("schedule_count is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleCountEqualTo(Integer value) {
            addCriterion("schedule_count =", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountNotEqualTo(Integer value) {
            addCriterion("schedule_count <>", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountGreaterThan(Integer value) {
            addCriterion("schedule_count >", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("schedule_count >=", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountLessThan(Integer value) {
            addCriterion("schedule_count <", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountLessThanOrEqualTo(Integer value) {
            addCriterion("schedule_count <=", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountIn(List<Integer> values) {
            addCriterion("schedule_count in", values, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountNotIn(List<Integer> values) {
            addCriterion("schedule_count not in", values, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountBetween(Integer value1, Integer value2) {
            addCriterion("schedule_count between", value1, value2, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("schedule_count not between", value1, value2, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitIsNull() {
            addCriterion("schedule_limit is null");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitIsNotNull() {
            addCriterion("schedule_limit is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitEqualTo(Integer value) {
            addCriterion("schedule_limit =", value, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitNotEqualTo(Integer value) {
            addCriterion("schedule_limit <>", value, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitGreaterThan(Integer value) {
            addCriterion("schedule_limit >", value, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("schedule_limit >=", value, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitLessThan(Integer value) {
            addCriterion("schedule_limit <", value, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitLessThanOrEqualTo(Integer value) {
            addCriterion("schedule_limit <=", value, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitIn(List<Integer> values) {
            addCriterion("schedule_limit in", values, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitNotIn(List<Integer> values) {
            addCriterion("schedule_limit not in", values, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitBetween(Integer value1, Integer value2) {
            addCriterion("schedule_limit between", value1, value2, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("schedule_limit not between", value1, value2, "scheduleLimit");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusIsNull() {
            addCriterion("schedule_status is null");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusIsNotNull() {
            addCriterion("schedule_status is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusEqualTo(Integer value) {
            addCriterion("schedule_status =", value, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusNotEqualTo(Integer value) {
            addCriterion("schedule_status <>", value, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusGreaterThan(Integer value) {
            addCriterion("schedule_status >", value, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("schedule_status >=", value, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusLessThan(Integer value) {
            addCriterion("schedule_status <", value, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusLessThanOrEqualTo(Integer value) {
            addCriterion("schedule_status <=", value, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusIn(List<Integer> values) {
            addCriterion("schedule_status in", values, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusNotIn(List<Integer> values) {
            addCriterion("schedule_status not in", values, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusBetween(Integer value1, Integer value2) {
            addCriterion("schedule_status between", value1, value2, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andScheduleStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("schedule_status not between", value1, value2, "scheduleStatus");
            return (Criteria) this;
        }

        public Criteria andCondition1IsNull() {
            addCriterion("condition1 is null");
            return (Criteria) this;
        }

        public Criteria andCondition1IsNotNull() {
            addCriterion("condition1 is not null");
            return (Criteria) this;
        }

        public Criteria andCondition1EqualTo(Byte value) {
            addCriterion("condition1 =", value, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1NotEqualTo(Byte value) {
            addCriterion("condition1 <>", value, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1GreaterThan(Byte value) {
            addCriterion("condition1 >", value, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1GreaterThanOrEqualTo(Byte value) {
            addCriterion("condition1 >=", value, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1LessThan(Byte value) {
            addCriterion("condition1 <", value, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1LessThanOrEqualTo(Byte value) {
            addCriterion("condition1 <=", value, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1In(List<Byte> values) {
            addCriterion("condition1 in", values, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1NotIn(List<Byte> values) {
            addCriterion("condition1 not in", values, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1Between(Byte value1, Byte value2) {
            addCriterion("condition1 between", value1, value2, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition1NotBetween(Byte value1, Byte value2) {
            addCriterion("condition1 not between", value1, value2, "condition1");
            return (Criteria) this;
        }

        public Criteria andCondition2IsNull() {
            addCriterion("condition2 is null");
            return (Criteria) this;
        }

        public Criteria andCondition2IsNotNull() {
            addCriterion("condition2 is not null");
            return (Criteria) this;
        }

        public Criteria andCondition2EqualTo(Byte value) {
            addCriterion("condition2 =", value, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2NotEqualTo(Byte value) {
            addCriterion("condition2 <>", value, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2GreaterThan(Byte value) {
            addCriterion("condition2 >", value, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2GreaterThanOrEqualTo(Byte value) {
            addCriterion("condition2 >=", value, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2LessThan(Byte value) {
            addCriterion("condition2 <", value, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2LessThanOrEqualTo(Byte value) {
            addCriterion("condition2 <=", value, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2In(List<Byte> values) {
            addCriterion("condition2 in", values, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2NotIn(List<Byte> values) {
            addCriterion("condition2 not in", values, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2Between(Byte value1, Byte value2) {
            addCriterion("condition2 between", value1, value2, "condition2");
            return (Criteria) this;
        }

        public Criteria andCondition2NotBetween(Byte value1, Byte value2) {
            addCriterion("condition2 not between", value1, value2, "condition2");
            return (Criteria) this;
        }

        public Criteria andFailMsgIsNull() {
            addCriterion("fail_msg is null");
            return (Criteria) this;
        }

        public Criteria andFailMsgIsNotNull() {
            addCriterion("fail_msg is not null");
            return (Criteria) this;
        }

        public Criteria andFailMsgEqualTo(String value) {
            addCriterion("fail_msg =", value, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgNotEqualTo(String value) {
            addCriterion("fail_msg <>", value, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgGreaterThan(String value) {
            addCriterion("fail_msg >", value, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgGreaterThanOrEqualTo(String value) {
            addCriterion("fail_msg >=", value, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgLessThan(String value) {
            addCriterion("fail_msg <", value, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgLessThanOrEqualTo(String value) {
            addCriterion("fail_msg <=", value, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgLike(String value) {
            addCriterion("fail_msg like", value, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgNotLike(String value) {
            addCriterion("fail_msg not like", value, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgIn(List<String> values) {
            addCriterion("fail_msg in", values, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgNotIn(List<String> values) {
            addCriterion("fail_msg not in", values, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgBetween(String value1, String value2) {
            addCriterion("fail_msg between", value1, value2, "failMsg");
            return (Criteria) this;
        }

        public Criteria andFailMsgNotBetween(String value1, String value2) {
            addCriterion("fail_msg not between", value1, value2, "failMsg");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatePinIsNull() {
            addCriterion("create_pin is null");
            return (Criteria) this;
        }

        public Criteria andCreatePinIsNotNull() {
            addCriterion("create_pin is not null");
            return (Criteria) this;
        }

        public Criteria andCreatePinEqualTo(String value) {
            addCriterion("create_pin =", value, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinNotEqualTo(String value) {
            addCriterion("create_pin <>", value, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinGreaterThan(String value) {
            addCriterion("create_pin >", value, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinGreaterThanOrEqualTo(String value) {
            addCriterion("create_pin >=", value, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinLessThan(String value) {
            addCriterion("create_pin <", value, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinLessThanOrEqualTo(String value) {
            addCriterion("create_pin <=", value, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinLike(String value) {
            addCriterion("create_pin like", value, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinNotLike(String value) {
            addCriterion("create_pin not like", value, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinIn(List<String> values) {
            addCriterion("create_pin in", values, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinNotIn(List<String> values) {
            addCriterion("create_pin not in", values, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinBetween(String value1, String value2) {
            addCriterion("create_pin between", value1, value2, "createPin");
            return (Criteria) this;
        }

        public Criteria andCreatePinNotBetween(String value1, String value2) {
            addCriterion("create_pin not between", value1, value2, "createPin");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdatePinIsNull() {
            addCriterion("update_pin is null");
            return (Criteria) this;
        }

        public Criteria andUpdatePinIsNotNull() {
            addCriterion("update_pin is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatePinEqualTo(String value) {
            addCriterion("update_pin =", value, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinNotEqualTo(String value) {
            addCriterion("update_pin <>", value, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinGreaterThan(String value) {
            addCriterion("update_pin >", value, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinGreaterThanOrEqualTo(String value) {
            addCriterion("update_pin >=", value, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinLessThan(String value) {
            addCriterion("update_pin <", value, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinLessThanOrEqualTo(String value) {
            addCriterion("update_pin <=", value, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinLike(String value) {
            addCriterion("update_pin like", value, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinNotLike(String value) {
            addCriterion("update_pin not like", value, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinIn(List<String> values) {
            addCriterion("update_pin in", values, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinNotIn(List<String> values) {
            addCriterion("update_pin not in", values, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinBetween(String value1, String value2) {
            addCriterion("update_pin between", value1, value2, "updatePin");
            return (Criteria) this;
        }

        public Criteria andUpdatePinNotBetween(String value1, String value2) {
            addCriterion("update_pin not between", value1, value2, "updatePin");
            return (Criteria) this;
        }

        public Criteria andSysVersionIsNull() {
            addCriterion("sys_version is null");
            return (Criteria) this;
        }

        public Criteria andSysVersionIsNotNull() {
            addCriterion("sys_version is not null");
            return (Criteria) this;
        }

        public Criteria andSysVersionEqualTo(Integer value) {
            addCriterion("sys_version =", value, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionNotEqualTo(Integer value) {
            addCriterion("sys_version <>", value, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionGreaterThan(Integer value) {
            addCriterion("sys_version >", value, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_version >=", value, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionLessThan(Integer value) {
            addCriterion("sys_version <", value, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionLessThanOrEqualTo(Integer value) {
            addCriterion("sys_version <=", value, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionIn(List<Integer> values) {
            addCriterion("sys_version in", values, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionNotIn(List<Integer> values) {
            addCriterion("sys_version not in", values, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionBetween(Integer value1, Integer value2) {
            addCriterion("sys_version between", value1, value2, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andSysVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_version not between", value1, value2, "sysVersion");
            return (Criteria) this;
        }

        public Criteria andYnIsNull() {
            addCriterion("yn is null");
            return (Criteria) this;
        }

        public Criteria andYnIsNotNull() {
            addCriterion("yn is not null");
            return (Criteria) this;
        }

        public Criteria andYnEqualTo(Byte value) {
            addCriterion("yn =", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotEqualTo(Byte value) {
            addCriterion("yn <>", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnGreaterThan(Byte value) {
            addCriterion("yn >", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnGreaterThanOrEqualTo(Byte value) {
            addCriterion("yn >=", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnLessThan(Byte value) {
            addCriterion("yn <", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnLessThanOrEqualTo(Byte value) {
            addCriterion("yn <=", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnIn(List<Byte> values) {
            addCriterion("yn in", values, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotIn(List<Byte> values) {
            addCriterion("yn not in", values, "yn");
            return (Criteria) this;
        }

        public Criteria andYnBetween(Byte value1, Byte value2) {
            addCriterion("yn between", value1, value2, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotBetween(Byte value1, Byte value2) {
            addCriterion("yn not between", value1, value2, "yn");
            return (Criteria) this;
        }

        public Criteria andTsIsNull() {
            addCriterion("ts is null");
            return (Criteria) this;
        }

        public Criteria andTsIsNotNull() {
            addCriterion("ts is not null");
            return (Criteria) this;
        }

        public Criteria andTsEqualTo(Date value) {
            addCriterion("ts =", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotEqualTo(Date value) {
            addCriterion("ts <>", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThan(Date value) {
            addCriterion("ts >", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThanOrEqualTo(Date value) {
            addCriterion("ts >=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThan(Date value) {
            addCriterion("ts <", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThanOrEqualTo(Date value) {
            addCriterion("ts <=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsIn(List<Date> values) {
            addCriterion("ts in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotIn(List<Date> values) {
            addCriterion("ts not in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsBetween(Date value1, Date value2) {
            addCriterion("ts between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotBetween(Date value1, Date value2) {
            addCriterion("ts not between", value1, value2, "ts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule_task
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule_task
     *
     * @mbg.generated Thu Oct 17 23:47:09 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}